### ISSUE TITLE
Missing Details

### ISSUE THREAD

**Issue by ChiragAJain** [WiOSc/Wios-New-Web#7]
- [x] **Update Events Page with recently conducted events.** 
- [x] **Update LTS Page with Webverse series and remove the other series**
- [x] **Update members of 2023 i.e. add missing members and their social media links** _(images can be found on the club's Instagram  
          page, inspect the page, and find the source link, 
          Member details: https://docs.google.com/spreadsheets/d/11HohdzSIJriT0jrPPktPVLXvF6l2swlCo3TWWqb_dFE/edit?usp=sharing)_

**The details of events and LTS will be provided in the Tech Team group and in discord**
**Finish it on or before 28th December**

**Comment by arnnnavvvvv** [comment]
I'll be working on updating the LTS page.

**Comment by Ramya-Panditi** [comment]
I'll update the members

**Comment by oipithesecond** [comment]
I will start working on updating the events page
